//! The LLM text format (`prompt.py`): the character sheet, the turn prompt, and
//! the reply parser.
//!
//! The split between code and data is deliberate (prompt.md §6.2): **all**
//! LLM-visible prose lives in `assets/prompts/` — the prose body in `turn.j2`,
//! the sheet's micro-strings in `strings.toml` — while every decision (who is
//! visible, which offers show, how far away someone is, how the JSON is
//! escaped) stays here. The template receives fully-computed values and does no
//! filtering, ordering or formatting of its own.
//!
//! The rendered prompt is byte-diffed against fixtures generated by the Python
//! HEAD (`tests/golden_prompts.rs`), so the layout in this module is behavior.

pub mod json_fmt;
pub mod parse;

use minijinja::{AutoEscape, Environment, context};
use serde::{Deserialize, Serialize};

use crate::{
    HEARING_RADIUS_M, ITEM_INTERACTION_RADIUS_M,
    character::Character,
    error::PromptError,
    ids::{ActorId, ItemId},
    offer::Offer,
    world::World,
};

pub use json_fmt::{PyAsciiFormatter, py_round, to_py_json};
pub use parse::{ParsedAction, REPLY_MUST_BE_TEXT, parse_reply, parse_reply_value};

/// The one template `assets/prompts/turn.j2` is registered under.
const TURN_TEMPLATE: &str = "turn.j2";

/// The LLM-visible strings the sheet embeds (`assets/prompts/strings.toml`).
///
/// They are not in `turn.j2` because the sheet is serialized before templating;
/// they are not in Rust because they are prose the model reads (D3).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PromptStrings {
    /// Rendered instead of the real name of anyone outside `knows`.
    pub unknown_person_name: String,
    /// `you_see.description`.
    pub you_see_description: String,
    /// `since_your_last_turn` when nothing happened.
    pub nothing: String,
    /// `recent_history` when nothing has happened yet.
    pub nothing_yet: String,
    /// `you_offer[].to` for a broadcast offer.
    pub offer_to_anyone: String,
    /// `the_only_languages_you_know`.
    pub languages: String,
    /// `offered_to_you[].accept_with`, with `%s` standing for the item id.
    pub accept_with: String,
}

impl PromptStrings {
    fn accept_with(&self, item_id: &ItemId) -> String {
        self.accept_with.replacen("%s", item_id.as_str(), 1)
    }
}

/// The prompt renderer: the compiled template plus the sheet's strings.
///
/// Build it once at startup from the two `assets/prompts/` files. There is no
/// embedded fallback — a missing or broken file is a hard error, because a
/// silently baked-in prompt is exactly what the data files exist to prevent
/// (prompt.md §6.3, R11).
pub struct PromptEnv {
    environment: Environment<'static>,
    strings: PromptStrings,
}

impl std::fmt::Debug for PromptEnv {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PromptEnv")
            .field("strings", &self.strings)
            .finish_non_exhaustive()
    }
}

impl PromptEnv {
    /// `turn_template` is the text of `assets/prompts/turn.j2`, `strings_toml`
    /// that of `assets/prompts/strings.toml`. The host reads the files; the sim
    /// crate never touches the filesystem.
    ///
    /// The minijinja settings are all `[BYTE]`-load-bearing: without
    /// `keep_trailing_newline` the prompt loses its final `\n`, and autoescape
    /// would HTML-escape the quotes in the sheet JSON.
    pub fn new(turn_template: &str, strings_toml: &str) -> Result<Self, PromptError> {
        let strings: PromptStrings = toml::from_str(strings_toml)
            .map_err(|error| PromptError::new(format!("invalid prompt strings: {error}")))?;
        if !strings.accept_with.contains("%s") {
            return Err(PromptError::new(
                "prompt strings: accept_with must contain the '%s' item-id placeholder",
            ));
        }

        let mut environment = Environment::new();
        environment.set_keep_trailing_newline(true);
        environment.set_auto_escape_callback(|_| AutoEscape::None);
        environment
            .add_template_owned(TURN_TEMPLATE, turn_template.to_string())
            .map_err(|error| PromptError::new(format!("invalid prompt template: {error}")))?;

        Ok(Self {
            environment,
            strings,
        })
    }

    pub fn strings(&self) -> &PromptStrings {
        &self.strings
    }
}

// ---------------------------------------------------------------------------
// The character sheet. Field order is normative (`prompt.py:215-238`): serde
// serializes struct fields in declaration order, which is why these are structs
// and not `serde_json::Map`s (which would sort alphabetically).
// ---------------------------------------------------------------------------

#[derive(Serialize)]
struct Sheet<'a> {
    name: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    lore_profile: Option<PromptLoreProfile<'a>>,
    back_story: &'a str,
    you_are: YouAre,
    you_hold: Vec<ItemRef<'a>>,
    /// Omitted entirely when empty — not rendered as `[]` (`prompt.py:227`).
    #[serde(skip_serializing_if = "Vec::is_empty")]
    you_offer: Vec<YouOffer<'a>>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    offered_to_you: Vec<OfferedToYou<'a>>,
    you_see: YouSee<'a>,
    since_your_last_turn: Vec<&'a str>,
    recent_history: Vec<&'a str>,
    stored_memories: &'a [String],
    the_only_languages_you_know: &'a str,
    /// Always a string: a cleared goal is the literal `"None"` (D15).
    current_goal: &'a str,
}

/// The compact, always-relevant portion of a lore record. The potentially
/// long extended description stays authoritative in the sim but is reserved
/// for a future introspection mechanism rather than paid for on every turn.
#[derive(Serialize)]
struct PromptLoreProfile<'a> {
    age: u16,
    gender: &'a str,
    occupation_id: Option<&'a str>,
    occupation: Option<&'a str>,
    title: Option<&'a str>,
    rank: Option<&'a str>,
    faction_role: Option<&'a str>,
    illegal_activity: Option<&'a str>,
    district: &'a str,
    father: Option<LoreRelation<'a>>,
    mother: Option<LoreRelation<'a>>,
    children: Vec<LoreRelation<'a>>,
    statuses: &'a [String],
    conditions: &'a [String],
}

#[derive(Serialize)]
struct LoreRelation<'a> {
    id: &'a ActorId,
    name: String,
}

#[derive(Serialize)]
struct YouAre {
    location_description: String,
    /// The office, as a short phrase — the clock reaches the model here, not as
    /// a percept (`features/movement/01_the_clock.md` §7). Omitted when the host
    /// carries no clock, which keeps the frozen golden fixtures byte-identical.
    #[serde(skip_serializing_if = "Option::is_none")]
    the_hour: Option<String>,
    position_m: Position,
}

/// `Vec3.to_json()`. The fields are `f64` even when integral, so `114.0` renders
/// as `114.0` and not `114`.
#[derive(Serialize)]
struct Position {
    x: f64,
    y: f64,
    z: f64,
}

#[derive(Serialize)]
struct ItemRef<'a> {
    id: &'a ItemId,
    name: &'a str,
}

/// `_person` (`prompt.py:144-155`): `distance_m` only appears in `you_see`.
#[derive(Serialize)]
struct Person<'a> {
    id: &'a ActorId,
    name: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    distance_m: Option<f64>,
}

#[derive(Serialize)]
struct YouOffer<'a> {
    item: ItemRef<'a>,
    to: OfferTo<'a>,
}

#[derive(Serialize)]
#[serde(untagged)]
enum OfferTo<'a> {
    /// A broadcast offer — or, quirk intact, one whose target has left the
    /// world (`prompt.py:186-196`; R9/R21: replicate, do not "fix").
    Anyone(&'a str),
    Person(Person<'a>),
}

#[derive(Serialize)]
struct OfferedToYou<'a> {
    item: ItemRef<'a>,
    from: Person<'a>,
    accept_with: String,
}

#[derive(Serialize)]
struct YouSee<'a> {
    description: &'a str,
    people: Vec<Person<'a>>,
}

fn person<'a>(
    actor: &Character,
    other: &'a Character,
    strings: &'a PromptStrings,
    distance_m: Option<f64>,
) -> Person<'a> {
    Person {
        id: other.id(),
        name: if actor.knows().contains(other.id()) {
            other.name()
        } else {
            &strings.unknown_person_name
        },
        distance_m: distance_m.map(|distance| py_round(distance, 1)),
    }
}

/// The global offer order both sheet sections follow (`prompt.py:162-163`).
/// `ItemId`'s `Ord` is UTF-8 byte order, which equals Python's `str` code-point
/// order.
fn offer_sort_key(offer: &Offer) -> (i64, &ItemId) {
    (offer.created_seq, &offer.item_id)
}

/// Render `actor_id`'s turn prompt.
///
/// `since` overrides `since_your_last_turn`; passing `None` reads the actor's
/// live inbox and mutates nothing (`prompt.py:214`) — the preview path used by
/// tests and tooling.
pub fn render_prompt(
    world: &World,
    actor_id: &ActorId,
    since: Option<&[String]>,
    env: &PromptEnv,
) -> Result<String, PromptError> {
    let Some(actor) = world.characters.get(actor_id) else {
        return Err(PromptError::new(format!("unknown actor '{actor_id}'")));
    };
    if !actor.control().is_llm() {
        return Err(PromptError::new(
            "the human-controlled player must never receive an LLM prompt",
        ));
    }
    let strings = &env.strings;

    let people: Vec<Person<'_>> = world
        .characters_within(actor.position_m(), HEARING_RADIUS_M, Some(actor_id))
        .iter()
        .map(|other_id| {
            let other = &world.characters[other_id];
            let distance = actor
                .position_m()
                .distance_squared(other.position_m())
                .sqrt();
            person(actor, other, strings, Some(distance))
        })
        .collect();

    let mut sorted_offers: Vec<&Offer> = world.offers.values().collect();
    sorted_offers.sort_by_key(|offer| offer_sort_key(offer));

    let mut you_offer: Vec<YouOffer<'_>> = Vec::new();
    let mut offered_to_you: Vec<OfferedToYou<'_>> = Vec::new();
    for offer in sorted_offers {
        // An offer of an item that has left the world shows in neither section.
        let Some(entity) = world.items.get(&offer.item_id) else {
            continue;
        };
        let item = ItemRef {
            id: &offer.item_id,
            name: &entity.name,
        };
        if offer.giver_id == *actor_id {
            let target = offer
                .target_id
                .as_ref()
                .and_then(|target_id| world.characters.get(target_id));
            you_offer.push(YouOffer {
                item,
                to: match target {
                    None => OfferTo::Anyone(&strings.offer_to_anyone),
                    Some(target) => OfferTo::Person(person(actor, target, strings, None)),
                },
            });
        } else if offer.target_id.is_none() || offer.target_id.as_ref() == Some(actor_id) {
            let Some(giver) = world.characters.get(&offer.giver_id) else {
                continue;
            };
            // Inclusive at exactly 4 m: only a strictly greater distance drops
            // the offer, so `offered_to_you` lists exactly what can be accepted.
            if actor.position_m().distance_squared(giver.position_m())
                > ITEM_INTERACTION_RADIUS_M * ITEM_INTERACTION_RADIUS_M
            {
                continue;
            }
            offered_to_you.push(OfferedToYou {
                item,
                from: person(actor, giver, strings, None),
                accept_with: strings.accept_with(&offer.item_id),
            });
        }
    }

    let events: &[String] = since.unwrap_or(actor.inbox());
    let since_your_last_turn = fallback(events, &strings.nothing);
    let recent_history = fallback(actor.recent_history(), &strings.nothing_yet);

    let position = actor.position_m();
    let location_description = world
        .area_map
        .location_description(position)
        .unwrap_or_else(|| actor.location_description().to_string());
    let relation = |id| LoreRelation {
        id,
        name: world
            .characters
            .get(id)
            .map_or_else(|| id.to_string(), |character| character.name().to_string()),
    };
    let lore_profile = actor.lore().map(|profile| PromptLoreProfile {
        age: profile.age,
        gender: &profile.gender,
        occupation_id: profile.occupation_id.as_deref(),
        occupation: profile.occupation_display.as_deref(),
        title: profile.title.as_deref(),
        rank: profile.rank.as_deref(),
        faction_role: profile.faction_role.as_deref(),
        illegal_activity: profile.illegal_activity.as_deref(),
        district: &profile.district,
        father: profile.father.as_ref().map(&relation),
        mother: profile.mother.as_ref().map(&relation),
        children: profile.children.iter().map(relation).collect(),
        statuses: &profile.statuses,
        conditions: &profile.conditions,
    });
    let sheet = Sheet {
        name: actor.name(),
        lore_profile,
        back_story: actor.back_story(),
        you_are: YouAre {
            location_description,
            the_hour: world.current_time.map(|time| {
                format!("{} — {}", time.office.label(), time.office.prompt_phrase())
            }),
            position_m: Position {
                x: position.x,
                y: position.y,
                z: position.z,
            },
        },
        you_hold: actor
            .holds()
            .iter()
            // A dangling id is silently skipped (`prompt.py:222-226`).
            .filter_map(|item_id| {
                world.items.get(item_id).map(|item| ItemRef {
                    id: item_id,
                    name: &item.name,
                })
            })
            .collect(),
        you_offer,
        offered_to_you,
        you_see: YouSee {
            description: &strings.you_see_description,
            people,
        },
        since_your_last_turn,
        recent_history,
        stored_memories: actor.memories(),
        the_only_languages_you_know: &strings.languages,
        current_goal: actor.goal(),
    };

    let sheet_json = to_py_json(&sheet).map_err(|error| {
        PromptError::new(format!("the character sheet did not serialize: {error}"))
    })?;
    let emittable_sounds = world.sound_catalog.emittable_sound_ids().join(", ");

    env.environment
        .get_template(TURN_TEMPLATE)
        .and_then(|template| {
            template.render(context! {
                sheet_json,
                sounds_enabled => world.sounds_enabled,
                emittable_sounds,
            })
        })
        .map_err(|error| PromptError::new(format!("the turn template did not render: {error}")))
}

/// `events or ["nothing"]` — the empty list is falsy in Python.
fn fallback<'a>(lines: &'a [String], empty: &'a str) -> Vec<&'a str> {
    if lines.is_empty() {
        vec![empty]
    } else {
        lines.iter().map(String::as_str).collect()
    }
}

/// Move the actor's inbox into a prompt, leaving a fresh inbox behind
/// (`prompt.py:243-261`).
///
/// Returns the prompt together with the percepts it presented as
/// `since_your_last_turn`. The caller graduates those into `recent_history`
/// with [`Character::absorb_presented_history`] once the turn *completes*; a
/// turn that never happens pushes them back onto the FRONT of
/// `pending_history`, so a retried prompt presents them as new instead of
/// showing the same line in both fields at once.
///
/// On a render error both lists are restored by **prepending**, so anything
/// that arrived mid-render stays behind them in chronological order.
pub fn render_prompt_and_drain(
    world: &mut World,
    actor_id: &ActorId,
    env: &PromptEnv,
) -> Result<(String, Vec<String>), PromptError> {
    let Some(actor) = world.characters.get_mut(actor_id) else {
        return Err(PromptError::new(format!("unknown actor '{actor_id}'")));
    };
    let drained = std::mem::take(&mut actor.state.inbox);
    let presented = actor.take_pending_history();

    match render_prompt(world, actor_id, Some(&drained), env) {
        Ok(rendered) => Ok((rendered, presented)),
        Err(error) => {
            let actor = world
                .characters
                .get_mut(actor_id)
                .expect("the actor existed a moment ago");
            prepend(&mut actor.state.inbox, drained);
            prepend(&mut actor.state.pending_history, presented);
            Err(error)
        }
    }
}

fn prepend(target: &mut Vec<String>, mut front: Vec<String>) {
    front.append(target);
    *target = front;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_accept_with_pattern_takes_the_item_id() {
        let strings = PromptStrings {
            unknown_person_name: "x".into(),
            you_see_description: "x".into(),
            nothing: "nothing".into(),
            nothing_yet: "nothing yet".into(),
            offer_to_anyone: "anyone".into(),
            languages: "English".into(),
            accept_with: r#"accept_offered_item {"item_id": "%s"}"#.into(),
        };
        assert_eq!(
            strings.accept_with(&ItemId::from_raw("fzbn9")),
            r#"accept_offered_item {"item_id": "fzbn9"}"#
        );
    }

    #[test]
    fn a_strings_file_without_the_placeholder_is_rejected() {
        let error = PromptEnv::new("x", "unknown_person_name = \"a\"\nyou_see_description = \"b\"\nnothing = \"c\"\nnothing_yet = \"d\"\noffer_to_anyone = \"e\"\nlanguages = \"f\"\naccept_with = \"no placeholder\"\n")
            .unwrap_err();
        assert!(error.message.contains("%s"), "{}", error.message);
    }
}
